source "https://rubygems.org"

# Specify your gem's dependencies in refresher.gemspec
gemspec
gem "standard"
gem "bundle"

# required by logger to colorize output
gem "colorize" # add color to logging

group :development do
  gem "rake"
  gem "rspec"
  gem "pry-byebug"
  gem "guard"
  gem "guard-shell"
  gem "guard-rspec"
end
